-- EMPLOYEE becomes implicit: every active person is one, so it stops being a
-- row anyone can hold, grant or revoke.
--
-- WHY THIS IS SAFE — the whole argument, because it is an access change.
--
-- EMPLOYEE granted exactly ONE thing: the `spend-report` menu. Submit and My
-- Requests never consulted roles at all (canAccessPageV2 returns true for
-- both unconditionally), and EMPLOYEE appears in no other entry of
-- FREE_MENU_DEFAULTS and in no WORKFLOW_MENUS.
--
-- And `spend-report` already listed EVERY other role too — BO, CEO,
-- ACCOUNTING, PROCUREMENT, PETTY_CASH_CUSTODIAN — with SUPERADMIN passing the
-- unconditional bypass. So every person who held any role row already had it,
-- and after this change every ACTIVE person has it via hasRoleV2's implicit
-- answer. Nobody gains or loses a menu. Verified by diffing the full access
-- matrix, generated by calling the app's own permission functions, before and
-- after: zero differences across 38 people.
--
-- What it does NOT grant remains unchanged: spend-report SCOPE is a separate
-- gate (people.visible_departments -> spendScopeV2), so the 14 active people
-- with no department still see an empty report, exactly as before.
--
-- WHAT REPLACES THE ROWS: lib/access-v2.ts#hasRoleV2 answers true for
-- EMPLOYEE whenever the person is active. One line, one place. Auto-
-- registration and the Add-person route no longer write the row, so the
-- tables cannot drift back.
--
-- REVERSIBLE: every removed row is kept in person_roles_employee_snapshot_037
-- with its original created_at. To undo:
--
--   insert into public.person_roles (email, role, created_at)
--   select email, role, created_at from public.person_roles_employee_snapshot_037
--   on conflict (email, role) do nothing;
--
-- ...alongside reverting the code, which is what actually decides access.

create table if not exists public.person_roles_employee_snapshot_037 (
  email text not null,
  role text not null,
  created_at timestamptz not null,
  snapshot_at timestamptz not null default now(),
  primary key (email, role)
);

insert into public.person_roles_employee_snapshot_037 (email, role, created_at)
select email, role, created_at from public.person_roles where role = 'EMPLOYEE'
on conflict (email, role) do nothing;

delete from public.person_roles where role = 'EMPLOYEE';

-- The CHECK still ALLOWS 'EMPLOYEE'. Deliberate: narrowing it would make the
-- rollback statement above fail at exactly the moment it is needed. The
-- application is what refuses to write the row (ASSIGNABLE_ROLES in
-- lib/access-v2.ts, enforced server-side in PUT /api/users-access).

alter table public.person_roles_employee_snapshot_037 enable row level security;

comment on table public.person_roles_employee_snapshot_037 is
  'The 21 EMPLOYEE rows removed by migration 037, kept so the change is reversible in one statement. EMPLOYEE is now implicit for every active person.';
